name: tt_pos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  sqflite: ^2.3.0
  path: ^1.8.3
  mobile_scanner: ^5.0.0
  provider: ^6.1.2

  # Printer & PDF
  esc_pos_utils_plus: ^2.0.3
  pdf: ^3.10.8
  printing: ^5.11.1
  file_picker: ^8.1.2
  blue_thermal_printer: ^1.2.3 # NDK/CMake Mismatch ကင်းစင်သော Pure Android Plugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
